#! /bin/bash

## TODO - this is not portable across build environments
## Convert this to ant

## Need the following for jar
#export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home"
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

version=`cat ../SMTFeature/feature.xml | head | grep -v encoding | grep "version=" | sed -e 's/ //g' -e 's/version=\"//' -e 's/\"//'`
echo Building version $version
cat src/org/smtlib/resources/version.template | sed -e "s/DEV/${version}/" > src/org/smtlib/resources/version.properties
mkdir -p bin/org/smtlib/resources
cp src/org/smtlib/resources/version.properties bin/org/smtlib/resources/version.properties

rm -rf temp
mkdir temp
echo "Manifest-Version: 1.0" > temp/manifest
echo "Main-Class: org.smtlib.SMT" >> temp/manifest
cd bin
rm -f jsmtlib.properties
"$JAVA_HOME/bin/jar" -cfm ../jSMTLIB.jar ../temp/manifest .
cp ../jsmtlib.properties .
cd ..
#/Users/tony/tools/apache-ant-1.9.7/bin/ant -f javadoc.xml
ant -f javadoc.xml
#cp ../../../../texstuff/papers/SMTLIBUserGuide/SMTLIBUserGuide.pdf jSMTLIBUserGuide.pdf
#tar cf jSMTLIB.tar jSMTLIB.jar LICENSE jSMTLIBUserGuide.pdf jsmtlib.properties-template doc
#rm -f jSMTLIBUserGuide.pdf
#tar tvf jSMTLIB.tar
#rm -f jSMTLIB.tar.gz
#gzip jSMTLIB.tar

echo Build complete

#export OPENJML=../../../../eworkspaces/OpenJMLgit/OpenJML
#if [ -e $OPENJML/OpenJML ] ; then cp jSMTLIB.jar $OPENJML/OpenJML ; else echo Copy failed ; fi
#if [ -e $OPENJML/OpenJMLUI ] ; then cp jSMTLIB.jar $OPENJML/OpenJMLUI ; else echo Copy failed; fi
#export OPENJML=../../../../../OpenJML-git-java8/OpenJML
#if [ -e $OPENJML/OpenJML ] ; then cp jSMTLIB.jar $OPENJML/OpenJML ; else echo Copy failed ; fi
#if [ -e $OPENJML/OpenJMLUI ] ; then cp jSMTLIB.jar $OPENJML/OpenJMLUI ; else echo Copy failed; fi
#echo Copies complete
